server:
  port: 8080

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo?useSSL=false
    username: root
    password: 12345678
    druid:
      initial-size: 1
      max-active: 20
      min-idle: 1
      max-wait: 60000
      pool-prepared-statements: true
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filters: config,stat,wall,slf4j
      connection-properties: useUnicode=true;characterEncoding=UTF-8;autoReconnect=true;useSSL=false;durid.stat.slowSqlMillis=5000;durid.stat.mergeSql=true;config.decrypt=true;config.decrypt.key=MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALgW4oIylIVnX8AKjm+kefx5EG/VOEas/BtYXz86DeAZ43I+NWcTsviUmj5lHYvGi7aqHRF5KvZMjcX7t2otS5sCAwEAAQ==
      use-global-datasource-stat: true
      remove-abandoned: true
      remove-abandoned-timeout: 1800
      log-abandoned: true

pagehelper:
  helper-dialect: mysql

# 日志配置文件
logging:
  config: classpath:logback.xml

mybatis:
  executor-type: REUSE
  mapperLocations: classpath:/mapper/**/*.xml

  cache:
    redis:
      use-key-prefix: true
      time-to-live: 1d
  redis:
    #redis不配置database时，默认为0库
    #database: 7
    host: 127.0.0.1
    port: 6379
    password:
    lettuce:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8

redisson:
  address: redis://127.0.0.1:6379
